version: '3.8'

services:

  nginx-load-balancer:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  nginx:
    image: nginx:latest
    deploy:
      replicas: 5
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  spring-app:
    image: mbahurau/docker-bootcamp:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DEVOPS: "Mikita Bahurau"
    ports:
      - "${SPRING_PORT}:8080"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
